### ISSUE TITLE
pip3 fails to install fts-rest client

### ISSUE THREAD

**Issue by paulmillar** [cern-fts/fts-rest#19]
When I attempt to install fts-rest package using python3 (== `pip3`) the installation fails:

```
paul@sprocket:~$ pip3 install fts3-rest
Collecting fts3-rest
  Using cached https://files.pythonhosted.org/packages/3d/06/e5bb9d6b78ef6a93cef4a9f161f9e46e8694ae9de649cffa03fed31d8542/fts3-rest-3.9.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9zcbjuzw/fts3-rest/setup.py", line 15
        print "Applying workaround for M2Crypto in RedHat"
                                                         ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Applying workaround for M2Crypto in RedHat")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9zcbjuzw/fts3-rest/
paul@sprocket:~$ 
``` 

It looks like this `print` statement (mistakenly) follows the [old (python 2) syntax](https://python-future.org/compatible_idioms.html#print).

**Comment by paulmillar** [comment]
Thanks for the explanation Mihai,

I'm not using the FTS client very often, so this isn't so urgent.

Also, as long as python v2 is working, I don't _need_ to use python v3 (but see #18).

Working with RPMs is somewhat awkward on my Debian machine, but (if needs must) I can probably do something to make it work.

Cheers,
Paul.
